import { useEffect, useState } from 'react'
import { Link, useOutletContext } from 'react-router-dom'
import Loading from '../components/Loading'
import { candidateApi, cvUrl } from '../services/api'

const sources = ['FACEBOOK', 'LINKEDIN', 'WEBSITE', 'REFERRAL', 'JOB_SITE', 'OTHER']
export default function CandidatesPage() {
  const { user } = useOutletContext(); const canEdit = ['ADMIN', 'HR'].includes(user.role)
  const [filters, setFilters] = useState({ keyword: '', source: '' }); const [state, setState] = useState({ loading: true, rows: [], error: '' })
  function load(query = filters) { setState((s) => ({ ...s, loading: true, error: '' })); const p = new URLSearchParams(); if (query.keyword) p.set('keyword', query.keyword); if (query.source) p.set('source', query.source); candidateApi.list(p.toString() ? `?${p}` : '').then((r) => setState({ loading: false, rows: r.data, error: '' })).catch((e) => setState({ loading: false, rows: [], error: e.message })) }
  useEffect(() => { candidateApi.list().then((result) => setState({ loading: false, rows: result.data, error: '' })).catch((error) => setState({ loading: false, rows: [], error: error.message })) }, [])
  async function remove(id) { if (!window.confirm('Bạn có chắc muốn xóa ứng viên này?')) return; try { await candidateApi.remove(id); load() } catch (error) { setState((s) => ({ ...s, error: error.message })) } }
  return <><div className="d-flex justify-content-between align-items-center mb-3"><div><h1 className="h3 mb-1">Ứng viên</h1><p className="text-muted mb-0">Quản lý thông tin và CV ứng viên.</p></div>{canEdit && <Link className="btn btn-primary" to="/candidates/create">Thêm ứng viên</Link>}</div><form className="card card-body shadow-sm border-0 mb-3" onSubmit={(e) => { e.preventDefault(); load() }}><div className="row g-2"><div className="col-md-8"><input className="form-control" value={filters.keyword} onChange={(e) => setFilters({ ...filters, keyword: e.target.value })} placeholder="Họ tên, email, điện thoại hoặc kỹ năng" /></div><div className="col-md-2"><select className="form-select" value={filters.source} onChange={(e) => setFilters({ ...filters, source: e.target.value })}><option value="">Tất cả nguồn</option>{sources.map((source) => <option key={source}>{source}</option>)}</select></div><div className="col-md-2 d-grid"><button className="btn btn-outline-primary">Tìm kiếm</button></div></div></form>{state.error && <div className="alert alert-danger">{state.error}</div>}{state.loading ? <Loading /> : <div className="table-responsive shadow-sm"><table className="table table-hover mb-0"><thead className="table-light"><tr><th>ID</th><th>Họ tên</th><th>Email</th><th>Điện thoại</th><th>Kỹ năng</th><th>Nguồn</th><th>CV</th><th>Thao tác</th></tr></thead><tbody>{state.rows.length === 0 ? <tr><td colSpan="8" className="text-center text-muted py-4">Chưa có ứng viên.</td></tr> : state.rows.map((candidate) => <tr key={candidate.id}><td>{candidate.id}</td><td className="fw-semibold">{candidate.full_name}</td><td>{candidate.email || '-'}</td><td>{candidate.phone || '-'}</td><td>{candidate.skills || '-'}</td><td>{candidate.source}</td><td>{candidate.cv_file ? <a href={cvUrl(candidate.cv_file)} target="_blank" rel="noreferrer">Xem CV</a> : '-'}</td><td className="text-nowrap"><Link className="btn btn-sm btn-outline-primary me-1" to={`/candidates/${candidate.id}`}>Xem</Link>{canEdit && <><Link className="btn btn-sm btn-outline-secondary me-1" to={`/candidates/${candidate.id}/edit`}>Sửa</Link><button className="btn btn-sm btn-outline-danger" onClick={() => remove(candidate.id)}>Xóa</button></>}</td></tr>)}</tbody></table></div>}</>
}
