import { useEffect, useState } from 'react'
import { Link, useNavigate, useOutletContext, useParams } from 'react-router-dom'
import Loading from '../components/Loading'
import { candidateApi } from '../services/api'

const emptyCandidate = { full_name: '', email: '', phone: '', skills: '', experience: '', education: '', source: 'OTHER', cv_file: '' }
const sources = ['FACEBOOK', 'LINKEDIN', 'WEBSITE', 'REFERRAL', 'JOB_SITE', 'OTHER']
export default function CandidateFormPage() {
  const { user } = useOutletContext(); const { id } = useParams(); const navigate = useNavigate(); const editing = Boolean(id)
  const [form, setForm] = useState(emptyCandidate); const [cv, setCv] = useState(null); const [state, setState] = useState({ loading: editing, saving: false, error: '' })
  useEffect(() => { if (!editing) return; candidateApi.get(id).then((r) => { setForm(r.data); setState({ loading: false, saving: false, error: '' }) }).catch((e) => setState({ loading: false, saving: false, error: e.message })) }, [editing, id])
  if (!['ADMIN', 'HR'].includes(user.role)) return <div className="alert alert-danger">Bạn không có quyền thay đổi ứng viên.</div>
  if (state.loading) return <Loading />
  async function submit(event) { event.preventDefault(); setState({ ...state, saving: true, error: '' }); const data = new FormData(); ['full_name','email','phone','skills','experience','education','source'].forEach((name) => data.append(name, form[name] || '')); if (cv) data.append('cv', cv); try { if (editing) await candidateApi.update(id, data); else await candidateApi.create(data); navigate('/candidates') } catch (error) { setState({ ...state, saving: false, error: error.message }) } }
  const field = (name) => ({ value: form[name] ?? '', onChange: (e) => setForm({ ...form, [name]: e.target.value }) })
  return <div className="form-page mx-auto"><div className="d-flex justify-content-between mb-3"><h1 className="h3">{editing ? 'Sửa ứng viên' : 'Thêm ứng viên'}</h1><Link className="btn btn-outline-secondary" to="/candidates">Quay lại</Link></div>{state.error && <div className="alert alert-danger">{state.error}</div>}<form className="card card-body shadow-sm border-0" onSubmit={submit}><div className="row g-3"><div className="col-md-6"><label className="form-label">Họ tên *</label><input className="form-control" {...field('full_name')} /></div><div className="col-md-6"><label className="form-label">Email</label><input className="form-control" type="email" {...field('email')} /></div><div className="col-md-6"><label className="form-label">Điện thoại</label><input className="form-control" {...field('phone')} /></div><div className="col-md-6"><label className="form-label">Nguồn</label><select className="form-select" {...field('source')}>{sources.map((s) => <option key={s}>{s}</option>)}</select></div><div className="col-12"><label className="form-label">Kỹ năng</label><input className="form-control" {...field('skills')} /></div><div className="col-md-6"><label className="form-label">Kinh nghiệm</label><textarea className="form-control" rows="3" {...field('experience')} /></div><div className="col-md-6"><label className="form-label">Học vấn</label><textarea className="form-control" rows="3" {...field('education')} /></div><div className="col-12"><label className="form-label">CV (PDF, DOC, DOCX; tối đa 10 MB)</label><input className="form-control" type="file" accept=".pdf,.doc,.docx" onChange={(e) => setCv(e.target.files[0] || null)} />{editing && form.cv_file && <div className="form-text">Không chọn file mới để giữ <a href={`/uploads/${form.cv_file}`} target="_blank" rel="noreferrer">CV hiện tại</a>.</div>}</div></div><div className="mt-4"><button className="btn btn-primary" disabled={state.saving}>{state.saving ? 'Đang lưu...' : 'Lưu ứng viên'}</button></div></form></div>
}

