import { useEffect, useState } from 'react'
import { Link, useOutletContext } from 'react-router-dom'
import Loading from '../components/Loading'
import { jobApi } from '../services/api'

export default function JobsPage() {
  const { user } = useOutletContext(); const canEdit = ['ADMIN', 'HR'].includes(user.role)
  const [filters, setFilters] = useState({ keyword: '', status: '' }); const [state, setState] = useState({ loading: true, rows: [], error: '' })
  function loadJobs(query = filters) { setState((current) => ({ ...current, loading: true, error: '' })); const params = new URLSearchParams(); if (query.keyword) params.set('keyword', query.keyword); if (query.status) params.set('status', query.status); const suffix = params.toString() ? `?${params}` : ''; jobApi.list(suffix).then((result) => setState({ loading: false, rows: result.data, error: '' })).catch((error) => setState({ loading: false, rows: [], error: error.message })) }
  useEffect(() => { jobApi.list().then((result) => setState({ loading: false, rows: result.data, error: '' })).catch((error) => setState({ loading: false, rows: [], error: error.message })) }, [])
  async function remove(id) { if (!window.confirm('Bạn có chắc muốn xóa vị trí này?')) return; try { await jobApi.remove(id); loadJobs() } catch (error) { setState((current) => ({ ...current, error: error.message })) } }
  return <><div className="d-flex justify-content-between align-items-center mb-3"><div><h1 className="h3 mb-1">Vị trí tuyển dụng</h1><p className="text-muted mb-0">Tìm kiếm và quản lý các vị trí.</p></div>{canEdit && <Link className="btn btn-primary" to="/jobs/create">Thêm vị trí</Link>}</div><form className="card card-body shadow-sm border-0 mb-3" onSubmit={(e) => { e.preventDefault(); loadJobs() }}><div className="row g-2"><div className="col-md-8"><input className="form-control" value={filters.keyword} onChange={(e) => setFilters({ ...filters, keyword: e.target.value })} placeholder="Tên vị trí, phòng ban hoặc kỹ năng" /></div><div className="col-md-2"><select className="form-select" value={filters.status} onChange={(e) => setFilters({ ...filters, status: e.target.value })}><option value="">Tất cả trạng thái</option><option>OPEN</option><option>CLOSED</option></select></div><div className="col-md-2 d-grid"><button className="btn btn-outline-primary">Tìm kiếm</button></div></div></form>{state.error && <div className="alert alert-danger">{state.error}</div>}{state.loading ? <Loading /> : <div className="table-responsive shadow-sm"><table className="table table-hover mb-0"><thead className="table-light"><tr><th>ID</th><th>Tên vị trí</th><th>Phòng ban</th><th>Kỹ năng</th><th>Số lượng</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>{state.rows.length === 0 ? <tr><td colSpan="7" className="text-center text-muted py-4">Chưa có vị trí tuyển dụng.</td></tr> : state.rows.map((job) => <tr key={job.id}><td>{job.id}</td><td className="fw-semibold">{job.title}</td><td>{job.department || '-'}</td><td>{job.skills || '-'}</td><td>{job.quantity}</td><td><span className={`badge text-bg-${job.status === 'OPEN' ? 'success' : 'secondary'}`}>{job.status}</span></td><td className="text-nowrap"><Link className="btn btn-sm btn-outline-primary me-1" to={`/jobs/${job.id}`}>Xem</Link>{canEdit && <><Link className="btn btn-sm btn-outline-secondary me-1" to={`/jobs/${job.id}/edit`}>Sửa</Link><button className="btn btn-sm btn-outline-danger" onClick={() => remove(job.id)}>Xóa</button></>}</td></tr>)}</tbody></table></div>}</>
}
